eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://localhost:8901/eureka/
      # 不对自己注册
    register-with-eureka: false
  server:
    # 关闭自我保护,如果不在线的服务会被服务中心直接剔除不保留 开发模式使用,生产环境禁止
    enable-self-preservation: false
spring:
  application:
    #服务名字
    name: eureka


server:
  port: 8761

